// IMPORTANTE: Los tabs deben mantenerse en orden alfabético por label
// REGLA: Los colores siguen secuencia arcoíris (red, orange, yellow, green, teal, cyan, blue, indigo, violet, purple, pink, rose) repitiendo ciclo
import type { TabConfig } from "@/components/MyTab";

export const parametrosTabs: TabConfig[] = [
  {
    id: "actividades",
    label: "Actividades",
    tipo: "actividades",
    color: "red",
    columns: [
      { key: "habilitado", label: "H", defaultWidth: 32, type: "boolean", align: "center" },
      { key: "nombre", label: "Nombre", defaultWidth: 200, type: "text" },
      { key: "unidad", label: "Unidad", defaultWidth: 150, type: "text" },
      { key: "descripcion", label: "Descripción", defaultWidth: 200, type: "text" },
      { key: "propietario", label: "Propietario", defaultWidth: 120, type: "text" },
    ],
  },
  {
    id: "bancos",
    label: "Bancos",
    tipo: "bancos",
    color: "orange",
    columns: [
      { key: "habilitado", label: "H", defaultWidth: 32, type: "boolean", align: "center" },
      { key: "transferencia", label: "T", defaultWidth: 32, type: "boolean", align: "center" },
      { key: "nombre", label: "Nombre", defaultWidth: 200, type: "text" },
      { key: "descripcion", label: "Descripción", defaultWidth: 200, type: "text" },
      { key: "propietario", label: "Propietario", defaultWidth: 120, type: "text" },
    ],
  },
  {
    id: "cargas",
    label: "Cargas",
    tipo: "cargas",
    color: "yellow",
    columns: [
      { key: "habilitado", label: "H", defaultWidth: 32, type: "boolean", align: "center" },
      { key: "nombre", label: "Nombre", defaultWidth: 200, type: "text" },
      { key: "unidad", label: "Unidad", defaultWidth: 120, type: "text" },
      { key: "descripcion", label: "Descripción", defaultWidth: 200, type: "text" },
      { key: "propietario", label: "Propietario", defaultWidth: 120, type: "text" },
    ],
  },
  {
    id: "cargos_finca",
    label: "Cargos Finca",
    tipo: "cargos finca",
    color: "green",
    columns: [
      { key: "habilitado", label: "H", defaultWidth: 32, type: "boolean", align: "center" },
      { key: "nombre", label: "Nombre", defaultWidth: 200, type: "text" },
      { key: "valor", label: "Sueldo/día $", defaultWidth: 120, type: "number", align: "right" },
      { key: "unidad", label: "Unidad", defaultWidth: 120, type: "text" },
    ],
  },
  {
    id: "cargos_nucleo",
    label: "Cargos Núcleo",
    tipo: "cargos nucleo",
    color: "teal",
    columns: [
      { key: "habilitado", label: "H", defaultWidth: 32, type: "boolean", align: "center" },
      { key: "nombre", label: "Nombre", defaultWidth: 200, type: "text" },
      { key: "valor", label: "Sueldo/día $", defaultWidth: 120, type: "number", align: "right" },
      { key: "unidad", label: "Unidad", defaultWidth: 120, type: "text" },
    ],
  },
  {
    id: "categorias",
    label: "Categorias",
    tipo: "categorias",
    color: "cyan",
    columns: [
      { key: "habilitado", label: "H", defaultWidth: 32, type: "boolean", align: "center" },
      { key: "nombre", label: "Nombre", defaultWidth: 200, type: "text" },
      { key: "unidad", label: "Unidad", defaultWidth: 120, type: "text" },
      { key: "descripcion", label: "Descripción", defaultWidth: 200, type: "text" },
      { key: "propietario", label: "Propietario", defaultWidth: 120, type: "text" },
    ],
  },
  {
    id: "central",
    label: "Centrales",
    tipo: "central",
    color: "blue",
    columns: [
      { key: "habilitado", label: "H", defaultWidth: 32, type: "boolean", align: "center" },
      { key: "nombre", label: "Nombre", defaultWidth: 200, type: "text" },
      { key: "unidad", label: "Unidad", defaultWidth: 120, type: "text" },
      { key: "propietario", label: "Propietario", defaultWidth: 120, type: "text" },
    ],
  },
  {
    id: "chofer",
    label: "Choferes",
    tipo: "chofer",
    color: "indigo",
    columns: [
      { key: "habilitado", label: "H", defaultWidth: 32, type: "boolean", align: "center" },
      { key: "nombre", label: "Nombre", defaultWidth: 180, type: "text" },
      { key: "unidad", label: "Unidad", defaultWidth: 120, type: "text" },
      { key: "ced_rif", label: "Cédula", defaultWidth: 120, type: "text" },
      { key: "telefono", label: "Teléfono", defaultWidth: 120, type: "text" },
      { key: "cuenta", label: "Cuenta", defaultWidth: 150, type: "text" },
      { key: "propietario", label: "Propietario", defaultWidth: 120, type: "text" },
    ],
  },
  {
    id: "ciclos",
    label: "Ciclos",
    tipo: "ciclo",
    color: "violet",
    columns: [
      { key: "habilitado", label: "H", defaultWidth: 32, type: "boolean", align: "center" },
      { key: "nombre", label: "Nombre", defaultWidth: 200, type: "text" },
      { key: "unidad", label: "Unidad", defaultWidth: 120, type: "text" },
      { key: "descripcion", label: "Descripción", defaultWidth: 200, type: "text" },
      { key: "propietario", label: "Propietario", defaultWidth: 120, type: "text" },
    ],
  },
  {
    id: "claves",
    label: "Claves",
    tipo: "claves",
    color: "purple",
    columns: [
      { key: "habilitado", label: "H", defaultWidth: 32, type: "boolean", align: "center" },
      { key: "nombre", label: "Nombre", defaultWidth: 200, type: "text" },
      { key: "descripcion", label: "Descripción", defaultWidth: 200, type: "text" },
      { key: "propietario", label: "Propietario", defaultWidth: 120, type: "text" },
    ],
  },
  {
    id: "clientes",
    label: "Clientes",
    tipo: "clientes",
    color: "pink",
    columns: [
      { key: "habilitado", label: "H", defaultWidth: 32, type: "boolean", align: "center" },
      { key: "nombre", label: "Nombre", defaultWidth: 180, type: "text" },
      { key: "unidad", label: "Unidad", defaultWidth: 120, type: "text" },
      { key: "direccion", label: "Dirección", defaultWidth: 200, type: "text" },
      { key: "ced_rif", label: "Cédula/RIF", defaultWidth: 120, type: "text" },
      { key: "telefono", label: "Teléfono", defaultWidth: 120, type: "text" },
      { key: "propietario", label: "Propietario", defaultWidth: 120, type: "text" },
    ],
  },
  {
    id: "constantes",
    label: "Constantes",
    tipo: "constante",
    color: "rose",
    columns: [
      { key: "nombre", label: "Nombre", defaultWidth: 250, type: "text" },
      { key: "descripcion", label: "Valor", defaultWidth: 250, type: "text" },
    ],
  },
  {
    id: "cultivo",
    label: "Cultivos",
    tipo: "cultivo",
    color: "red",
    columns: [
      { key: "habilitado", label: "H", defaultWidth: 32, type: "boolean", align: "center" },
      { key: "nombre", label: "Nombre", defaultWidth: 200, type: "text" },
      { key: "unidad", label: "Unidad", defaultWidth: 120, type: "text" },
      { key: "descripcion", label: "Descripción", defaultWidth: 200, type: "text" },
      { key: "propietario", label: "Propietario", defaultWidth: 120, type: "text" },
    ],
  },
  {
    id: "destino",
    label: "Destino",
    tipo: "destino",
    color: "orange",
    columns: [
      { key: "habilitado", label: "H", defaultWidth: 32, type: "boolean", align: "center" },
      { key: "nombre", label: "Nombre", defaultWidth: 200, type: "text" },
      { key: "unidad", label: "Unidad", defaultWidth: 120, type: "text" },
      { key: "direccion", label: "Dirección", defaultWidth: 200, type: "text" },
      { key: "propietario", label: "Propietario", defaultWidth: 120, type: "text" },
    ],
  },
  {
    id: "dolar",
    label: "Dólar",
    tipo: "dolar",
    color: "yellow",
    columns: [
      { key: "fecha", label: "Fecha", defaultWidth: 100, type: "date" },
      { key: "valor", label: "Valor", defaultWidth: 120, type: "number" },
      { key: "propietario", label: "Propietario", defaultWidth: 120, type: "text" },
    ],
  },
  {
    id: "equiposred",
    label: "Equipos de Red",
    tipo: "equiposred",
    color: "green",
    columns: [
      { key: "habilitado", label: "H", defaultWidth: 32, type: "boolean", align: "center" },
      { key: "nombre", label: "Nombre", defaultWidth: 200, type: "text" },
      { key: "unidad", label: "Unidad", defaultWidth: 120, type: "text" },
      { key: "descripcion", label: "Descripción", defaultWidth: 200, type: "text" },
      { key: "propietario", label: "Propietario", defaultWidth: 120, type: "text" },
    ],
  },
  {
    id: "fincas",
    label: "Fincas",
    tipo: "fincas",
    color: "teal",
    columns: [
      { key: "habilitado", label: "H", defaultWidth: 32, type: "boolean", align: "center" },
      { key: "nombre", label: "Nombre", defaultWidth: 200, type: "text" },
      { key: "descripcion", label: "Código", defaultWidth: 120, type: "text" },
      { key: "unidad", label: "Unidad", defaultWidth: 120, type: "text" },
      { key: "propietario", label: "Propietario", defaultWidth: 120, type: "text" },
    ],
  },
  {
    id: "insumos",
    label: "Insumos",
    tipo: "insumos",
    color: "cyan",
    columns: [
      { key: "habilitado", label: "H", defaultWidth: 32, type: "boolean", align: "center" },
      { key: "nombre", label: "Nombre", defaultWidth: 200, type: "text" },
      { key: "unidad", label: "Unidad", defaultWidth: 120, type: "text" },
      { key: "descripcion", label: "Descripción", defaultWidth: 200, type: "text" },
      { key: "propietario", label: "Propietario", defaultWidth: 120, type: "text" },
    ],
  },
  {
    id: "formadepago",
    label: "Operaciones",
    tipo: "formadepago",
    color: "blue",
    columns: [
      { key: "habilitado", label: "H", defaultWidth: 32, type: "boolean", align: "center" },
      { key: "nombre", label: "Nombre", defaultWidth: 200, type: "text" },
      { key: "unidad", label: "Unidad", defaultWidth: 120, type: "text" },
      { key: "operador", label: "Operador", defaultWidth: 100, type: "text" },
      { key: "propietario", label: "Propietario", defaultWidth: 120, type: "text" },
    ],
  },
  {
    id: "origen",
    label: "Origen",
    tipo: "origen",
    color: "indigo",
    columns: [
      { key: "habilitado", label: "H", defaultWidth: 32, type: "boolean", align: "center" },
      { key: "nombre", label: "Nombre", defaultWidth: 200, type: "text" },
      { key: "unidad", label: "Unidad", defaultWidth: 120, type: "text" },
      { key: "descripcion", label: "Descripción", defaultWidth: 200, type: "text" },
      { key: "propietario", label: "Propietario", defaultWidth: 120, type: "text" },
    ],
  },
  {
    id: "personal",
    label: "Personal",
    tipo: "personal",
    color: "violet",
    columns: [
      { key: "habilitado", label: "H", defaultWidth: 32, type: "boolean", align: "center" },
      { key: "nombre", label: "Nombre", defaultWidth: 180, type: "text" },
      { key: "categoria", label: "Cargo", defaultWidth: 140, type: "text" },
      { key: "ced_rif", label: "Cédula/RIF", defaultWidth: 120, type: "text" },
      { key: "telefono", label: "Teléfono", defaultWidth: 120, type: "text" },
      { key: "direccion", label: "Dirección", defaultWidth: 200, type: "text" },
      { key: "cuenta", label: "Cuenta", defaultWidth: 150, type: "text" },
      { key: "correo", label: "Correo", defaultWidth: 180, type: "text" },
      { key: "unidad", label: "Unidad", defaultWidth: 120, type: "text" },
      { key: "propietario", label: "Propietario", defaultWidth: 120, type: "text" },
    ],
  },
  {
    id: "personaldelnucleo",
    label: "Personal del Núcleo",
    tipo: "personaldelnucleo",
    color: "purple-light",
    columns: [
      { key: "habilitado", label: "H", defaultWidth: 32, type: "boolean", align: "center" },
      { key: "nombre", label: "Nombre", defaultWidth: 200, type: "text" },
      { key: "ced_rif", label: "Cédula", defaultWidth: 120, type: "text" },
      { key: "cuenta", label: "Cuenta", defaultWidth: 150, type: "text" },
      { key: "categoria", label: "Cargo", defaultWidth: 120, type: "text" },
      { key: "propietario", label: "Propietario", defaultWidth: 120, type: "text" },
    ],
  },
  {
    id: "placa",
    label: "Placas",
    tipo: "placa",
    color: "purple",
    columns: [
      { key: "habilitado", label: "H", defaultWidth: 32, type: "boolean", align: "center" },
      { key: "nombre", label: "Placa", defaultWidth: 120, type: "text" },
      { key: "unidad", label: "Unidad", defaultWidth: 120, type: "text" },
      { key: "proveedor", label: "Proveedor", defaultWidth: 150, type: "text" },
      { key: "chofer", label: "Chofer", defaultWidth: 150, type: "text" },
      { key: "descripcion", label: "Descripción", defaultWidth: 200, type: "text" },
      { key: "propietario", label: "Propietario", defaultWidth: 120, type: "text" },
    ],
  },
  {
    id: "planes",
    label: "Planes",
    tipo: "planes",
    color: "pink",
    columns: [
      { key: "habilitado", label: "H", defaultWidth: 32, type: "boolean", align: "center" },
      { key: "nombre", label: "Nombre", defaultWidth: 200, type: "text" },
      { key: "unidad", label: "Unidad", defaultWidth: 120, type: "text" },
      { key: "descripcion", label: "Descripción", defaultWidth: 200, type: "text" },
      { key: "direccion", label: "Monto", defaultWidth: 100, type: "number", align: "right" },
      { key: "telefono", label: "Monto $", defaultWidth: 100, type: "number", align: "right" },
      { key: "propietario", label: "Propietario", defaultWidth: 120, type: "text" },
    ],
  },
  {
    id: "productos",
    label: "Productos",
    tipo: "productos",
    color: "rose",
    columns: [
      { key: "habilitado", label: "H", defaultWidth: 32, type: "boolean", align: "center" },
      { key: "nombre", label: "Nombre", defaultWidth: 200, type: "text" },
      { key: "unidad", label: "Unidad", defaultWidth: 120, type: "text" },
      { key: "descripcion", label: "Descripción", defaultWidth: 200, type: "text" },
      { key: "propietario", label: "Propietario", defaultWidth: 120, type: "text" },
    ],
  },
  {
    id: "proveedores",
    label: "Proveedores",
    tipo: "proveedores",
    color: "red",
    columns: [
      { key: "habilitado", label: "H", defaultWidth: 32, type: "boolean", align: "center" },
      { key: "nombre", label: "Nombre", defaultWidth: 180, type: "text" },
      { key: "direccion", label: "Dirección", defaultWidth: 200, type: "text" },
      { key: "telefono", label: "Teléfono", defaultWidth: 120, type: "text" },
      { key: "ced_rif", label: "Cédula/RIF", defaultWidth: 120, type: "text" },
      { key: "correo", label: "Correo", defaultWidth: 180, type: "text" },
      { key: "cuenta", label: "Cuenta", defaultWidth: 150, type: "text" },
      { key: "unidad", label: "Unidad", defaultWidth: 120, type: "text" },
      { key: "propietario", label: "Propietario", defaultWidth: 120, type: "text" },
    ],
  },
  {
    id: "suministros",
    label: "Suministros",
    tipo: "suministro",
    color: "orange",
    columns: [
      { key: "habilitado", label: "H", defaultWidth: 32, type: "boolean", align: "center" },
      { key: "nombre", label: "Nombre", defaultWidth: 200, type: "text" },
      { key: "unidad", label: "Unidad", defaultWidth: 120, type: "text" },
      { key: "categoria", label: "Categoría", defaultWidth: 120, type: "text" },
      { key: "descripcion", label: "Descripción", defaultWidth: 200, type: "text" },
      { key: "propietario", label: "Propietario", defaultWidth: 120, type: "text" },
    ],
  },
  {
    id: "tablones",
    label: "Tablones",
    tipo: "tablones",
    color: "yellow",
    columns: [
      { key: "habilitado", label: "H", defaultWidth: 32, type: "boolean", align: "center" },
      { key: "nombre", label: "Nombre", defaultWidth: 200, type: "text" },
      { key: "unidad", label: "Unidad", defaultWidth: 120, type: "text" },
      { key: "hectareas", label: "Hectáreas", defaultWidth: 100, type: "number" },
      { key: "descripcion", label: "Descripción", defaultWidth: 200, type: "text" },
      { key: "propietario", label: "Propietario", defaultWidth: 120, type: "text" },
    ],
  },
  {
    id: "unidad",
    label: "Unidades",
    tipo: "unidad",
    color: "green",
    columns: [
      { key: "habilitado", label: "H", defaultWidth: 32, type: "boolean", align: "center" },
      { key: "nombre", label: "Nombre", defaultWidth: 180, type: "text" },
      { key: "direccion", label: "Dirección", defaultWidth: 200, type: "text" },
      { key: "ced_rif", label: "Cédula/RIF", defaultWidth: 120, type: "text" },
      { key: "telefono", label: "Teléfono", defaultWidth: 120, type: "text" },
      { key: "propietario", label: "Propietario", defaultWidth: 120, type: "text" },
    ],
  },
];
