// IMPORTANTE: Los tabs deben mantenerse en orden alfabético por label
import type { TabConfig } from "@/components/MyTab";

export const parametrosTabs: TabConfig[] = [
  {
    id: "actividades",
    label: "Actividades",
    tipo: "actividades",
    columns: [
      { key: "habilitado", label: "H", defaultWidth: 32, type: "boolean", align: "center" },
      { key: "nombre", label: "Nombre", defaultWidth: 200, type: "text" },
      { key: "unidad", label: "Unidad", defaultWidth: 150, type: "text" },
      { key: "descripcion", label: "Descripción", defaultWidth: 200, type: "text" },
      { key: "propietario", label: "Propietario", defaultWidth: 120, type: "text" },
    ],
  },
  {
    id: "almacenes",
    label: "Almacen",
    tipo: "almacenes",
    columns: [
      { key: "habilitado", label: "H", defaultWidth: 32, type: "boolean", align: "center" },
      { key: "nombre", label: "Nombre", defaultWidth: 200, type: "text" },
      { key: "unidad", label: "Unidad", defaultWidth: 120, type: "text" },
      { key: "categoria", label: "Categoría", defaultWidth: 120, type: "text" },
      { key: "descripcion", label: "Descripción", defaultWidth: 200, type: "text" },
      { key: "propietario", label: "Propietario", defaultWidth: 120, type: "text" },
    ],
  },
  {
    id: "bancos",
    label: "Bancos",
    tipo: "bancos",
    columns: [
      { key: "habilitado", label: "H", defaultWidth: 32, type: "boolean", align: "center" },
      { key: "transferencia", label: "T", defaultWidth: 32, type: "boolean", align: "center" },
      { key: "nombre", label: "Nombre", defaultWidth: 200, type: "text" },
      { key: "descripcion", label: "Descripción", defaultWidth: 200, type: "text" },
      { key: "propietario", label: "Propietario", defaultWidth: 120, type: "text" },
    ],
  },
  {
    id: "cargas",
    label: "Cargas",
    tipo: "cargas",
    columns: [
      { key: "habilitado", label: "H", defaultWidth: 32, type: "boolean", align: "center" },
      { key: "nombre", label: "Nombre", defaultWidth: 200, type: "text" },
      { key: "unidad", label: "Unidad", defaultWidth: 120, type: "text" },
      { key: "descripcion", label: "Descripción", defaultWidth: 200, type: "text" },
      { key: "propietario", label: "Propietario", defaultWidth: 120, type: "text" },
    ],
  },
  {
    id: "categorias",
    label: "Categorias",
    tipo: "categorias",
    columns: [
      { key: "habilitado", label: "H", defaultWidth: 32, type: "boolean", align: "center" },
      { key: "nombre", label: "Nombre", defaultWidth: 200, type: "text" },
      { key: "descripcion", label: "Descripción", defaultWidth: 200, type: "text" },
      { key: "propietario", label: "Propietario", defaultWidth: 120, type: "text" },
    ],
  },
  {
    id: "chofer",
    label: "Choferes",
    tipo: "chofer",
    columns: [
      { key: "habilitado", label: "H", defaultWidth: 32, type: "boolean", align: "center" },
      { key: "nombre", label: "Nombre", defaultWidth: 180, type: "text" },
      { key: "ced_rif", label: "Cédula", defaultWidth: 120, type: "text" },
      { key: "telefono", label: "Teléfono", defaultWidth: 120, type: "text" },
      { key: "cuenta", label: "Cuenta", defaultWidth: 150, type: "text" },
      { key: "propietario", label: "Propietario", defaultWidth: 120, type: "text" },
    ],
  },
  {
    id: "ciclos",
    label: "Ciclos",
    tipo: "ciclo",
    columns: [
      { key: "habilitado", label: "H", defaultWidth: 32, type: "boolean", align: "center" },
      { key: "nombre", label: "Nombre", defaultWidth: 200, type: "text" },
      { key: "descripcion", label: "Descripción", defaultWidth: 200, type: "text" },
      { key: "propietario", label: "Propietario", defaultWidth: 120, type: "text" },
    ],
  },
  {
    id: "claves",
    label: "Claves",
    tipo: "claves",
    columns: [
      { key: "habilitado", label: "H", defaultWidth: 32, type: "boolean", align: "center" },
      { key: "nombre", label: "Nombre", defaultWidth: 200, type: "text" },
      { key: "descripcion", label: "Descripción", defaultWidth: 200, type: "text" },
      { key: "propietario", label: "Propietario", defaultWidth: 120, type: "text" },
    ],
  },
  {
    id: "clientes",
    label: "Clientes",
    tipo: "clientes",
    columns: [
      { key: "habilitado", label: "H", defaultWidth: 32, type: "boolean", align: "center" },
      { key: "nombre", label: "Nombre", defaultWidth: 180, type: "text" },
      { key: "unidad", label: "Unidad", defaultWidth: 120, type: "text" },
      { key: "direccion", label: "Dirección", defaultWidth: 200, type: "text" },
      { key: "ced_rif", label: "Cédula/RIF", defaultWidth: 120, type: "text" },
      { key: "telefono", label: "Teléfono", defaultWidth: 120, type: "text" },
      { key: "propietario", label: "Propietario", defaultWidth: 120, type: "text" },
    ],
  },
  {
    id: "cultivo",
    label: "Cultivos",
    tipo: "cultivo",
    columns: [
      { key: "habilitado", label: "H", defaultWidth: 32, type: "boolean", align: "center" },
      { key: "nombre", label: "Nombre", defaultWidth: 200, type: "text" },
      { key: "descripcion", label: "Descripción", defaultWidth: 200, type: "text" },
      { key: "propietario", label: "Propietario", defaultWidth: 120, type: "text" },
    ],
  },
  {
    id: "destino",
    label: "Destino",
    tipo: "destino",
    columns: [
      { key: "habilitado", label: "H", defaultWidth: 32, type: "boolean", align: "center" },
      { key: "nombre", label: "Nombre", defaultWidth: 200, type: "text" },
      { key: "direccion", label: "Dirección", defaultWidth: 200, type: "text" },
      { key: "propietario", label: "Propietario", defaultWidth: 120, type: "text" },
    ],
  },
  {
    id: "dolar",
    label: "Dólar",
    tipo: "dolar",
    columns: [
      { key: "fecha", label: "Fecha", defaultWidth: 100, type: "date" },
      { key: "valor", label: "Valor", defaultWidth: 120, type: "number" },
      { key: "propietario", label: "Propietario", defaultWidth: 120, type: "text" },
    ],
  },
  {
    id: "equipos",
    label: "Equipos",
    tipo: "equipos",
    columns: [
      { key: "habilitado", label: "Ab", defaultWidth: 32, type: "boolean", align: "center" },
      { key: "nombre", label: "Nombre", defaultWidth: 200, type: "text" },
      { key: "descripcion", label: "Descripción", defaultWidth: 200, type: "text" },
      { key: "propietario", label: "Propietario", defaultWidth: 120, type: "text" },
    ],
  },
  {
    id: "fincas",
    label: "Fincas",
    tipo: "fincas",
    columns: [
      { key: "habilitado", label: "H", defaultWidth: 32, type: "boolean", align: "center" },
      { key: "nombre", label: "Nombre", defaultWidth: 200, type: "text" },
      { key: "descripcion", label: "Descripción", defaultWidth: 200, type: "text" },
      { key: "propietario", label: "Propietario", defaultWidth: 120, type: "text" },
    ],
  },
  {
    id: "insumos",
    label: "Insumos",
    tipo: "insumos",
    columns: [
      { key: "habilitado", label: "H", defaultWidth: 32, type: "boolean", align: "center" },
      { key: "nombre", label: "Nombre", defaultWidth: 200, type: "text" },
      { key: "unidad", label: "Unidad", defaultWidth: 120, type: "text" },
      { key: "descripcion", label: "Descripción", defaultWidth: 200, type: "text" },
      { key: "propietario", label: "Propietario", defaultWidth: 120, type: "text" },
    ],
  },
  {
    id: "formadepago",
    label: "Operaciones",
    tipo: "formadepago",
    columns: [
      { key: "habilitado", label: "H", defaultWidth: 32, type: "boolean", align: "center" },
      { key: "nombre", label: "Nombre", defaultWidth: 200, type: "text" },
      { key: "operador", label: "Operador", defaultWidth: 100, type: "text" },
      { key: "propietario", label: "Propietario", defaultWidth: 120, type: "text" },
    ],
  },
  {
    id: "origen",
    label: "Origen",
    tipo: "origen",
    columns: [
      { key: "habilitado", label: "H", defaultWidth: 32, type: "boolean", align: "center" },
      { key: "nombre", label: "Nombre", defaultWidth: 200, type: "text" },
      { key: "descripcion", label: "Descripción", defaultWidth: 200, type: "text" },
      { key: "propietario", label: "Propietario", defaultWidth: 120, type: "text" },
    ],
  },
  {
    id: "personal",
    label: "Personal",
    tipo: "personal",
    columns: [
      { key: "habilitado", label: "H", defaultWidth: 32, type: "boolean", align: "center" },
      { key: "nombre", label: "Nombre", defaultWidth: 180, type: "text" },
      { key: "ced_rif", label: "Cédula/RIF", defaultWidth: 120, type: "text" },
      { key: "telefono", label: "Teléfono", defaultWidth: 120, type: "text" },
      { key: "direccion", label: "Dirección", defaultWidth: 200, type: "text" },
      { key: "cuenta", label: "Cuenta", defaultWidth: 150, type: "text" },
      { key: "correo", label: "Correo", defaultWidth: 180, type: "text" },
      { key: "unidad", label: "Unidad", defaultWidth: 120, type: "text" },
      { key: "propietario", label: "Propietario", defaultWidth: 120, type: "text" },
    ],
  },
  {
    id: "placa",
    label: "Placas",
    tipo: "placa",
    columns: [
      { key: "habilitado", label: "H", defaultWidth: 32, type: "boolean", align: "center" },
      { key: "nombre", label: "Placa", defaultWidth: 120, type: "text" },
      { key: "proveedor", label: "Proveedor", defaultWidth: 150, type: "text" },
      { key: "chofer", label: "Chofer", defaultWidth: 150, type: "text" },
      { key: "descripcion", label: "Descripción", defaultWidth: 200, type: "text" },
      { key: "propietario", label: "Propietario", defaultWidth: 120, type: "text" },
    ],
  },
  {
    id: "planes",
    label: "Planes",
    tipo: "planes",
    columns: [
      { key: "habilitado", label: "H", defaultWidth: 32, type: "boolean", align: "center" },
      { key: "nombre", label: "Nombre", defaultWidth: 200, type: "text" },
      { key: "descripcion", label: "Descripción", defaultWidth: 200, type: "text" },
      { key: "propietario", label: "Propietario", defaultWidth: 120, type: "text" },
    ],
  },
  {
    id: "productos",
    label: "Productos",
    tipo: "productos",
    columns: [
      { key: "habilitado", label: "H", defaultWidth: 32, type: "boolean", align: "center" },
      { key: "nombre", label: "Nombre", defaultWidth: 200, type: "text" },
      { key: "unidad", label: "Unidad", defaultWidth: 120, type: "text" },
      { key: "descripcion", label: "Descripción", defaultWidth: 200, type: "text" },
      { key: "propietario", label: "Propietario", defaultWidth: 120, type: "text" },
    ],
  },
  {
    id: "proveedores",
    label: "Proveedores",
    tipo: "proveedores",
    columns: [
      { key: "habilitado", label: "H", defaultWidth: 32, type: "boolean", align: "center" },
      { key: "nombre", label: "Nombre", defaultWidth: 180, type: "text" },
      { key: "direccion", label: "Dirección", defaultWidth: 200, type: "text" },
      { key: "telefono", label: "Teléfono", defaultWidth: 120, type: "text" },
      { key: "ced_rif", label: "Cédula/RIF", defaultWidth: 120, type: "text" },
      { key: "correo", label: "Correo", defaultWidth: 180, type: "text" },
      { key: "cuenta", label: "Cuenta", defaultWidth: 150, type: "text" },
      { key: "unidad", label: "Unidad", defaultWidth: 120, type: "text" },
      { key: "propietario", label: "Propietario", defaultWidth: 120, type: "text" },
    ],
  },
  {
    id: "tablones",
    label: "Tablones",
    tipo: "tablones",
    columns: [
      { key: "habilitado", label: "H", defaultWidth: 32, type: "boolean", align: "center" },
      { key: "nombre", label: "Nombre", defaultWidth: 200, type: "text" },
      { key: "unidad", label: "Unidad", defaultWidth: 120, type: "text" },
      { key: "hectareas", label: "Hectáreas", defaultWidth: 100, type: "number" },
      { key: "descripcion", label: "Descripción", defaultWidth: 200, type: "text" },
      { key: "propietario", label: "Propietario", defaultWidth: 120, type: "text" },
    ],
  },
  {
    id: "unidad",
    label: "Unidad",
    tipo: "unidad",
    columns: [
      { key: "habilitado", label: "H", defaultWidth: 32, type: "boolean", align: "center" },
      { key: "nombre", label: "Nombre", defaultWidth: 180, type: "text" },
      { key: "direccion", label: "Dirección", defaultWidth: 200, type: "text" },
      { key: "ced_rif", label: "Cédula/RIF", defaultWidth: 120, type: "text" },
      { key: "telefono", label: "Teléfono", defaultWidth: 120, type: "text" },
      { key: "propietario", label: "Propietario", defaultWidth: 120, type: "text" },
    ],
  },
];
